# Generated by Django 4.2.28 on 2026-03-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habitlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('study', 'Study'), ('work', 'Work'), ('mindful', 'Mindfulness'), ('home', 'Home'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='habit',
            name='frequency_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Specific weekdays'), ('interval', 'Every N days'), ('weekly_times', 'N times per week')], default='daily', max_length=20, verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='habit',
            name='icon',
            field=models.CharField(blank=True, max_length=8, verbose_name='Icon (emoji)'),
        ),
        migrations.AddField(
            model_name='habit',
            name='interval_days',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Interval days'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='habit',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='habit',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_enabled',
            field=models.BooleanField(default=False, verbose_name='Reminder enabled'),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Reminder time'),
        ),
        migrations.AddField(
            model_name='habit',
            name='target_unit',
            field=models.CharField(choices=[('times', 'times'), ('minutes', 'minutes'), ('pages', 'pages'), ('glasses', 'glasses'), ('km', 'km')], default='times', max_length=20, verbose_name='Target unit'),
        ),
        migrations.AddField(
            model_name='habit',
            name='target_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Target value'),
        ),
        migrations.AddField(
            model_name='habit',
            name='weekdays',
            field=models.JSONField(blank=True, default=list, verbose_name='Weekdays'),
        ),
        migrations.AddField(
            model_name='habit',
            name='weekly_times',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Times per week'),
        ),
        migrations.AddConstraint(
            model_name='habitlog',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='uniq_habit_date'),
        ),
        migrations.RemoveField(
            model_name='habitlog',
            name='comment',
        ),
    ]
